import Head from "next/head";

import styles from "@/styles/Home.module.css";

import { PitchPerfect } from "@/components/PerfectPitch";
import { CodeRefactor } from "@/components/CodeRefactor";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pitch Ai The Perfect Pitch Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PitchPerfect />
        <CodeRefactor />
      </main>
    </>
  );
}
